spring.application.name=product-microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/product-microservice
spring.datasource.username=root
spring.datasource.password=root
server.port=5000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
aws.accessKey.value=AKIAYVQ53JMHRF2DCYLK
aws.secretKey.value=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
aws.bucket.name=product12341234