spring.application.name=product-microservice
spring.datasource.url=jdbc:postgresql://postgres-product/product-microservice
spring.datasource.username=root
spring.datasource.password=root
server.port=3008
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.serviceUrl.defaultZone=http://discovery-microservice:8761/eureka
gc.bucket.name=clothing-e-commerce-images
google.cloud.credentials.location=file:/gcb/gifted-proxy-427415-p2-69f656e027c6.json
inventory.service.url=http://inventory-microservice/api/inventory
eureka.client.enabled=true
