spring.application.name=product-microservice
server.tomcat.basedir=/
spring.datasource.url=jdbc:postgresql://localhost:5433/product-microservice
spring.datasource.username=root
spring.datasource.password=root
server.port=3008
eureka.client.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
gc.bucket.name=clothing-e-commerce-images
order-microservice.url=http://order-microservice/api

google.cloud.credentials.location=file:${user.dir}/product-microservice/gifted-proxy-427415-p2-4ac3cc679362.json
logging.level.com.netflix.discovery=DEBUG


management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.event-consumer-buffer-size=10
resilience4j.circuitbreaker.configs.default.slidingWindowType=count_based
resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.circuitbreaker.instances.cartList.base-config=default
