spring.application.name=product-microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/product-microservice
spring.datasource.username=root
spring.datasource.password=root
server.port=3008
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
aws.bucket.name=product-microservice-images
inventory.service.url=http://inventory-microservice/api/inventory
