version: '3.8'

services:
    api-gateway:
      image: causeleea/api-gateway:v2.0
      ports:
        - "8181:8181"
      extra_hosts:
        - host.docker.internal:host-gateway
      container_name: api-gateway
      environment:
        SPRING_PROFILES_ACTIVE: docker
      restart: unless-stopped
      networks:
        - spring
    discovery-service:
      image: causeleea/discovery-microservice:v2.0
      ports:
        - "8761:8761"
      extra_hosts:
        - host.docker.internal:host-gateway
      container_name: discovery-microservice
      environment:
        SPRING_PROFILES_ACTIVE: docker
      networks:
        - spring
    product-microservice:
      image: causeleea/product-microservice:v2.0
      ports:
        - "3008:3008"
      extra_hosts:
        - host.docker.internal:host-gateway
      container_name: product-microservice
      environment:
        SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - discovery-service
        - postgres-product
      networks:
        - spring

    authentication-microservice:
      image: causeleea/authentication-microservice:v3.0
      ports:
        - "8182:8182"
      extra_hosts:
        - host.docker.internal:host-gateway
      container_name: authentication-microservice
      environment:
        SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - discovery-service
        - postgres-authentication
      networks:
        - spring

    cart-microservice:
      image: causeleea/cart-microservice:v2.0
      ports:
        - "3003:3003"
      extra_hosts:
        - host.docker.internal:host-gateway
      container_name: cart-microservice
      environment:
        SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - discovery-service
        - mongo-cart
      networks:
        - spring

    order-microservice:
      image: causeleea/order-microservice:v2.0
      ports:
        - "3002:3002"
      extra_hosts:
        - host.docker.internal:host-gateway
      container_name: order-microservice
      environment:
        SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - discovery-service
        - mongo-order
      networks:
        - spring

    points-microservice:
      image: causeleea/points-microservice:v2.0
      ports:
        - "3005:3005"
      extra_hosts:
        - host.docker.internal:host-gateway
      build:
        context: ./points-microservice
        dockerfile: Dockerfile
      container_name: points-microservice
      environment:
        SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - discovery-service
        - postgres-points
      networks:
        - spring


    wallet-microservice:
      image: causeleea/wallet-microservice:v2.0
      ports:
        - "3004:3004"
      extra_hosts:
        - host.docker.internal:host-gateway
      container_name: wallet-microservice
      environment:
        SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - discovery-service
        - postgres-wallet
      networks:
        - spring

    postgres-product:
      image: postgres:latest
      environment:
        POSTGRES_DB: product-microservice
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
      ports:
        - "5432:5432"
      restart: unless-stopped
      container_name: postgres-product
      volumes:
        - ./data/postgres/product-microservice:/data/postgres
        - ./init/postgres/product-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - spring


    postgres-wallet:
      image: postgres:latest
      environment:
        POSTGRES_DB: wallet-microservice
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
      ports:
        - "5433:5432"
      restart: unless-stopped
      container_name: postgres-wallet
      volumes:
        - ./data/postgres/wallet-microservice:/data/postgres
        - ./init/postgres/wallet-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - spring


    postgres-points:
      image: postgres:latest
      environment:
        POSTGRES_DB: points-microservice
        POSTGRES_USER : root
        POSTGRES_PASSWORD: root
      ports:
        - "5434:5432"
      restart: unless-stopped
      container_name: postgres-points
      volumes:
        - ./data/postgres/points-microservice:/data/postgres
        - ./init/postgres/points-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - spring


    postgres-authentication:
      image: postgres:latest
      restart: unless-stopped
      container_name: postgres-authentication
      ports:
        - "5436:5432"
      environment:
        POSTGRES_DB: authentication-microservice
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
      volumes:
        - ./data/postgres/authentication-microservice:/data/postgres
        - ./init/postgres/authentication-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - spring


    mongo-cart:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongo/cart-microservice:/data/db
        - ./init/mongo/cart-microservice/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      command: mongod --auth
      container_name: mongo-cart
      restart: unless-stopped
      networks:
        - spring

    mongo-order:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - "27019:27017"
      restart: unless-stopped
      container_name: mongo-order
      volumes:
        - ./data/mongo/order-microservice:/data/db
        - ./init/mongo/order-microservice/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      command: mongod --auth
      networks:
        - spring

networks:
  spring:
    driver: bridge