server.port=8181
spring.application.name=api-gateway
eureka.client.serviceUrl.defaultZone=http://discovery-microservice:8761/eureka
eureka.client.enabled=true

#gateway
##product Service
spring.cloud.gateway.routes[0].id=product-microservice`
spring.cloud.gateway.routes[0].uri=lb://product-microservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/**
##Discovery Service
spring.cloud.gateway.routes[1].id=discovery-microservice
spring.cloud.gateway.routes[1].uri=http://discovery-service:8761
spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[1].filters[0]=SetPath=/

##Discovery Service static route
spring.cloud.gateway.routes[2].id=discovery-service-static
spring.cloud.gateway.routes[2].uri=http://discovery-service:8761
spring.cloud.gateway.routes[2].predicates[0]=Path=/eureka/**

##review Service
spring.cloud.gateway.routes[3].id=review-microservice
spring.cloud.gateway.routes[3].uri=lb://review-microservice
#predicates defines conditions for routing , here all routing is based on path /api/review
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/review/**
spring.cloud.gateway.routes[3].filters[0]= AuthenticationFilter

##cart Service
spring.cloud.gateway.routes[4].id=cart-microservice
spring.cloud.gateway.routes[4].uri=lb://cart-microservice
#predicates defines conditions for routing , here all routing is based on path /api/auth
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/cart/**
spring.cloud.gateway.routes[4].filters[0]= AuthenticationFilter

spring.cloud.gateway.routes[5].id=authentication-microservice
spring.cloud.gateway.routes[5].uri=lb://authentication-microservice
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[5].filters[0]= AuthenticationFilter
#spring.cloud.gateway.routes[6].filters[1].args= org.springframework.util.String
spring.cloud.gateway.routes[6].id=wallet-microservice
spring.cloud.gateway.routes[6].uri=lb://wallet-microservice
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/wallet/**
spring.cloud.gateway.routes[6].filters[0]= AuthenticationFilter

spring.cloud.gateway.routes[7].id=order-microservice
spring.cloud.gateway.routes[7].uri=lb://order-microservice
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/order/**
spring.cloud.gateway.routes[7].filters[0]=AuthenticationFilter