version: '3.8'

services:
  postgres-product:
    image: postgres:latest
    environment:
      POSTGRES_DB: product-microservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: unless-stopped
    container_name: postgres-product
    volumes:
      - ./data/postgres/product-microservice:/data/postgres
      - ./init/postgres/product-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  postgres-user:
    image: postgres:latest
    environment:
      POSTGRES_DB: user-microservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    restart: unless-stopped
    container_name: postgres-user
    volumes:
      - ./data/postgres/user-microservice:/data/postgres
      - ./init/postgres/user-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring
      
  postgres-review:
    image: postgres:latest
    environment:
      POSTGRES_DB: review-microservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5430:5432"
    restart: unless-stopped
    container_name: postgres-review
    volumes:
      - ./data/postgres/review-microservice:/data/postgres
      - ./init/postgres/review-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring


  postgres-wallet:
    image: postgres:latest
    environment:
      POSTGRES_DB: wallet-microservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    restart: unless-stopped
    container_name: postgres-wallet
    volumes:
      - ./data/postgres/wallet-microservice:/data/postgres
      - ./init/postgres/wallet-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring


  postgres-points:
    image: postgres:latest
    environment:
      POSTGRES_DB: points-microservice
      POSTGRES_USER : root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    restart: unless-stopped
    volumes:
      - ./data/postgres/points-microservice:/data/postgres
      - ./init/postgres/points-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  mongo-cart:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/cart-microservice:/data/db
      - ./init/mongo/cart-microservice/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --auth
    networks:
      - spring


networks:
  spring:
    driver: bridge
