spring.application.name=inventory-microservice
server.port=3007
spring.datasource.url=jdbc:postgresql://host.docker.internal:5435/inventory-microservice
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.serviceUrl.defaultZone=http://discovery-microservice:8761/eureka


