spring.application.name=order-microservice

#server port
server.port=3002
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27019
spring.data.mongodb.database=order-service
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.authentication-database=admin


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka


product-microservice-url=http://product-microservice/api/product
inventory.microservice.url=http://inventory-microservice/api/inventory
points.microservice.url=http://points-microservice/api/points
aws.bucket.name=product-microservice-images


api.stripe.key=sk_test_51OwIReBXmkC83ALXrpTVYqTXC3bYPEQEeQ3OsMfB9V7ZRNpnGV53rTr6HnfEomYiRUVT0g5r2yhzO8bwwzZSfVQN00htdNO8ey