spring.application.name=order-service

#server port
server.port=3002
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=order-service
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.authentication-database=admin

user-microservice-url=http://localhost:3000/api/user
product-microservice-url=http://localhost:3001/api/user
