spring.application.name=review-microservice

spring.datasource.url=jdbc:postgresql://localhost:5430/review-microservice
spring.datasource.username=root
spring.datasource.password=root
server.port=3001
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

user-microservice.url=http://user-microservice/api/user
product-microservice.url=http://product-microservice/api/product