spring.application.name=authentication-microservice
server.port=8182
spring.datasource.url=jdbc:postgresql://localhost:5436/authentication-microservice
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
cart-microservice.url=http://cart-microservice/api/cart
points-microservice.url=http://points-microservice/api/points
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.enabled=true
