spring.application.name=authentication-microservice
server.port=8182
spring.datasource.url=jdbc:postgresql://postgres-authentication/authentication-microservice
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
cart-microservice.url=http://user-microservice/api/cart
points-microservice.url=http://user-microservice/api/points
eureka.client.serviceUrl.defaultZone=http://discovery-microservice:8761/eureka
eureka.client.enabled=true


