spring.application.name=order-microservice

#server port
server.port=3002
spring.data.mongodb.host=host.docker.internal
spring.data.mongodb.port=27019
spring.data.mongodb.database=order-service
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.authentication-database=admin


eureka.client.serviceUrl.defaultZone=http://discovery-microservice:8761/eureka
eureka.client.enabled=true


product-microservice-url=http://product-microservice/api/product
inventory.microservice.url=http://inventory-microservice/api/inventory
points.microservice.url=http://points-microservice/api/points
gc.bucket.name=clothing-e-commerce-images
google.cloud.credentials.location=file:/gcb/gifted-proxy-427415-p2-69f656e027c6.json

api.stripe.key=sk_test_51OwIReBXmkC83ALXrpTVYqTXC3bYPEQEeQ3OsMfB9V7ZRNpnGV53rTr6HnfEomYiRUVT0g5r2yhzO8bwwzZSfVQN00htdNO8ey