spring.application.name=order-microservice
spring.datasource.url=jdbc:postgresql://localhost:5434/order-microservice
spring.datasource.username=root
spring.datasource.password=root
server.port=3005
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.enabled=true

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27019
spring.data.mongodb.database=order-microservice
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.authentication-database=admin

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
product-microservice-url=http://product-microservice/api/product
points.microservice.url=http://points-microservice/api/points
gc.bucket.name=clothing-e-commerce-images
google.cloud.credentials.location=file:${user.dir}/product-microservice/gifted-proxy-427415-p2-69f656e027c6.json
api.stripe.key=sk_test_51OwIReBXmkC83ALXrpTVYqTXC3bYPEQEeQ3OsMfB9V7ZRNpnGV53rTr6HnfEomYiRUVT0g5r2yhzO8bwwzZSfVQN00htdNO8ey